#THIS IS SAMPLE FILE


browser: FF #acceptable values: FF, CHROME, GHOST
browser_ver: ANY
base-address: https://addons.mozilla.org #default testing wiki
live-domain: https://addons.mozilla.org/ #acceptable values: prod, preview, sandbox-number dev-name
credentialsPath: D:/selenium-config/config.xml #Path to your config.xml file
env: pro
platfrom: VISTA
runmode: local
platform-version: ANY
saucename:
saucekey:
#Config related with mobile devices
platfrom: ANDROID #acceptable values: IOS and ANDROID
platform-version: null #Example: 4.4 for Android 4.4
device-id: null #For Android devices uuid (can be obtained by running adb devices)
mobile-config:  #Path to your mobile-config.xml file
appium-ip: 127.0.0.1:4723 #Appium IP address with port ex. 127.0.0.1:4723 for local appium server
deviceName: ANDROID #capability for Appium server. For Android it can be any value.


