#THIS IS SAMPLE FILE
#Copy its content to config.yml file
#It is used only when you run tests using IDE

browser: FF #acceptable values: FF, CHROME, GHOST
base-address: https://addons.mozilla.org #default testing wiki
live-domain: https://addons.mozilla.org/ #acceptable values: prod, preview, sandbox-number dev-name
credentialsPath: c:/selenium-config/config.xml #Path to your config.xml file
captchaPath: c:/selenium-config/captcha.txt #Path to your captcha.txt file
env: pro
platfrom: VISTA
runmode: local
saucename:
saucekey:
#Config related with mobile devices
platfrom: ANDROID #acceptable values: IOS and ANDROID
platform-version: null #Example: 4.4 for Android 4.4
device-id: null #For Android devices uuid (can be obtained by running adb devices)
mobile-config:  #Path to your mobile-config.xml file
appium-ip: 127.0.0.1:4723 #Appium IP address with port ex. 127.0.0.1:4723 for local appium server
deviceName: ANDROID #capability for Appium server. For Android it can be any value.

env:
  global:
    - secure: PVLWgd9wXtfOJKJTFPi7hV/2/QBvwp1XHTH2Pz2K2nbjXqWWY7/Vwl/krFvEVyerRHybzJ97QVISHyRa4zLjGkszKWMu51Vynj9Zcy2TNXfJHSAURvMTWLdq2DmQSRXrBFo7884B7hcML7pVx23MT9vI65CIKTpSI5l7nZyyJXM=
    - secure: iH3zTrzZ6JYOIfeo+eMTt2Dfq0pKT2jvllfmyJIJF7Sje5Xs6p45DbuUedFkKSxEDmybtMXRCYTUW9hHzbPG1amzxxubQ6wAoJHPoo0JPaSb601vWxRoOse1ZHBNGLy/g8vra3BkiGIA95+64oAQlsdt6GM6PuZxIubmRYvfYTA=

